import Link from "next/link";
import "./globals.css";
import { Inter } from "next/font/google";
import LoginBtn from "./LoginBtn";
import { getServerSession } from "next-auth";
import { authOptions } from "@/pages/api/auth/[...nextauth]";
import LogoutBtn from "./LogoutBtn";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
    // 로그인된 유저정보 출력
    // 유저이름, 이메일 등
    let user = await getServerSession(authOptions);
    console.log(user);

    return (
        <html lang="en">
            <body className={inter.className}>
                <div className="navbar">
                    <Link href="/" className="logo">
                        Chan-Forum
                    </Link>
                    <Link href="/list">List</Link>
                    <Link href="/write">Write</Link>
                    <Link href="/signup">SignUp</Link>
                    {/* <LoginBtn /> */}
                    {user ? <LogoutBtn /> : <LoginBtn />}
                </div>
                {children}
            </body>
        </html>
    );
}
