import Link from "next/link";
import "./globals.css";
// import { Inter } from "next/font/google";
import LogoutBtn from "./LogoutBtn";
import LoginBtn from "./LoginBtn";
import { authOptions } from "@/pages/api/auth/[...nextauth]";
import { getServerSession } from "next-auth";
import { cookies } from "next/headers";
import DarkMode from "./DarkMode";

// const inter = Inter({ subsets: ["latin"] });

export const metadata = {
    title: "취업 좀 하자 제발",
    description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
    let user = await getServerSession(authOptions);

    let res = cookies().get("mode");
    console.log(res);

    return (
        <html lang="en">
            <body
                className={
                    res !== undefined && res.value === "dark"
                        ? "dark-mode"
                        : null
                }
            >
                <div className="navbar">
                    <Link href="/" className="logo">
                        Chan-Forum
                    </Link>
                    <Link href="/list">List</Link>
                    <Link href="/write">Write</Link>
                    <Link href="/register">SignUp</Link>
                    {user ? <LogoutBtn /> : <LoginBtn />}
                    <DarkMode />
                </div>
                {children}
            </body>
        </html>
    );
}
